version: '3.7'
services:
  redis:
    container_name: 'redis'
    image: redis:5.0.5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  nats:
    container_name: 'nats'
    image: nats:2.1.0
    ports:
      - "4222:4222"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper
  kafka:
#    container_name: 'kafka'
    image: wurstmeister/kafka:latest
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
#  pubsub:
#    container_name: 'pubsub'
#    image: emsa/pubsub:1.0.0
#    restart: on-failure
#    build:
#      context: ./..
#      dockerfile: ./docker/Dockerfile
#    depends_on:
#      - redis
#      - nats
#      - kafka
#    environment:
#      - REDIS_HOST=$REDIS_HOST
#      - NATS_HOST=$NATS_HOST
#      - KAFKA_HOST=$KAFKA_HOST
volumes:
  redis_data:

networks:
  default:
    name: blueprod_net
