version: '3.7'
services:
  redis:
    container_name: 'redis'
    image: redis:5.0.5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data:

networks:
  default:
    name: blueprod_net
